# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8041c3f6d806f6fabcfd31047ea62912aa13f35828c7a70d8a86c68743c30cd5b23ad159625b74e8219549910df0870e592e6e62138c5c2382ca10ce5346c5b8

test:
  secret_key_base: 916b266b1af951e76ae100419523891e33df28ca4f0d509e7633c5869423e333fe17bc6fdd7fc51c4dcc79c0905c677e84fb7ae1cbca3dc422a9a1740d030195

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
